# Generated by Django 4.2.5 on 2023-09-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_ingredient_amount_recipeingredient_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
    ]
