# Generated by Django 4.2.5 on 2023-09-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_recipeingredient_unique_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_recipe_tag',
        ),
    ]
