# Generated by Django 4.2.5 on 2023-09-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'список покупок', 'verbose_name_plural': 'Покупки'},
        ),
    ]
