# Generated by Django 4.2.5 on 2023-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_recipetag_unique_recipe_tag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
