# Generated by Django 4.2.5 on 2023-09-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_recipeingredient_unique_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(through='food.RecipeTag', to='food.tag', verbose_name='Тэги'),
        ),
    ]
