# Generated by Django 4.2.5 on 2023-09-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
