# Generated by Django 4.2.5 on 2023-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиентов', null=True, verbose_name='Количество'),
        ),
    ]
